// Code generated by nrdeco@; DO NOT EDIT.
//
// See here for more information on nrdeco: https://github.com/miyamo2/nrdeco
package usecase

import (
	"context"
	"github.com/newrelic/go-agent/v3/newrelic"
	"os"
	"strings"
	"github.com/miyamo2/nrdeco/examples/usecase"
)

// NRUserUseCase implements usecase.UserUseCase with New Relic instrumentation.
type NRUserUseCase struct {
	usecase.UserUseCase
}

func (n *NRUserUseCase) GetUserByIDWithContext(ctx context.Context, arg1 string) (*usecase.UserDto, error) {
	if strings.ToLower(os.Getenv("NRDECO_ENABLED")) == "true" {
		defer newrelic.FromContext(ctx).StartSegment("usecase.UserUseCase.GetUserByIDWithContext").End()
	}
	return n.UserUseCase.GetUserByIDWithContext(ctx, arg1)
}

func (n *NRUserUseCase) GetAllUsersWithContext(ctx context.Context) ([]usecase.UserDto, error) {
	if strings.ToLower(os.Getenv("NRDECO_ENABLED")) == "true" {
		defer newrelic.FromContext(ctx).StartSegment("usecase.UserUseCase.GetAllUsersWithContext").End()
	}
	return n.UserUseCase.GetAllUsersWithContext(ctx)
}
