// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/miyamo2/nrdeco/examples/interfaces"
	"net/http"
)

// Injectors from wire.go:

func ServeMux() *http.ServeMux {
	application := NewRelic()
	nrUserRepository := NewUserRepository()
	nrUserUseCase := NewUserUseCase(nrUserRepository)
	handler := interfaces.NewHandler(nrUserUseCase)
	serveMux := NewServeMux(application, handler)
	return serveMux
}
