name: Release

on:
  push:
    branches: [main]
    paths: ["CHANGELOG.md"]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.24"

    steps:
      - uses: Kesin11/actions-timeline@427ee2cf860166e404d0d69b4f2b24012bb7af4f # v2.2.3

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: go.sum

      - name: Extract Version
        id: versioning
        run: |
          VERSION="v$(sed -n 's/##\s\([0-9.]\+\(-\(alpha\|beta\)\.[0-9]\+\)\?\)\s.*/\1/p' CHANGELOG.md | head -1)"
          echo ::set-output name=version::$VERSION

      - name: Extract changes from prev version
        run: |
          git fetch --prune --unshallow
          PRETAG=$(git tag --sort -v:refname | head -1)
          CURRENTTAG=${{ steps.versioning.outputs.version }}
          echo "## What's Changed in ${CURRENTTAG}" > /tmp/diff-changelog.md
          if [ -z "$PRETAG" ]
          then
            cat CHANGELOG.md | sed -e 's/##\s[0-9.]*\s.*//g' >> /tmp/diff-changelog.md
          else
            git diff $PRETAG..${{ github.sha }} -- CHANGELOG.md | grep -E '^\+' | grep -v '+++' | sed -e 's/^\+//g' | sed -e 's/##\s[0-9.]*\s.*//g' | sed -e '/^$/d' >> /tmp/diff-changelog.md
            echo "" >> /tmp/diff-changelog.md
            echo "**Full Changelog**: https://github.com/miyamo2/nrdeco/compare/${PRETAG}...${CURRENTTAG}" >> /tmp/diff-changelog.md
          fi

      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.versioning.outputs.version }}
          git push origin ${{ steps.versioning.outputs.version }}

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: miyamo2

      - uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          version: latest
          args: release --clean --release-notes=/tmp/diff-changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ steps.generate-token.outputs.token }}